### ISSUE TITLE
Use USB-C to Lightning cable to control lightning device

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [stacksmashing/tamarin-c#1]
Hi there,

I have an iPhone SE which I **really** want to play around with. I was trying to get Linux to run on it but had some weird issue and having a debugger would help. The problem is lightning extension cables are too expensive in my area (2900/- rupee (or) 30$ USD).

So my question is, Can I just use a USB-C to Lightning cable and tamarin-c to debug the iPhone?

**Comment by nezza** [comment]
Hi, no, that won't work unfortunately

**Comment by ElectroBoy404NotFound** [comment]
Ah, ok. Thank you for your response!
